# Generated by Django 4.2.5 on 2023-11-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infant', models.IntegerField(help_text='8 year old')),
                ('infant_fees', models.IntegerField()),
                ('toddler', models.IntegerField(help_text='12 year old')),
                ('toddler_fees', models.IntegerField()),
                ('twaddler', models.IntegerField(help_text='16 year old')),
                ('twaddler_fees', models.IntegerField()),
                ('three_years_old', models.IntegerField(help_text='18 year old')),
                ('three_years_old_fees', models.IntegerField()),
                ('four_years_old', models.IntegerField(help_text='20 year old')),
                ('four_years_old_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone_number', models.BigIntegerField()),
                ('allergies', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('consent_form', models.FileField(default=False, upload_to='')),
                ('waiting_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HireStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('houly_salary', models.IntegerField()),
                ('terminate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignToClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(blank=True, max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facility.classroom')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facility.hirestaff')),
            ],
        ),
    ]
