# Generated by Django 4.2.5 on 2023-11-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollchild',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='four_years_old',
            field=models.IntegerField(help_text='4 year old'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='infant',
            field=models.IntegerField(help_text='0-1 year old'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='three_years_old',
            field=models.IntegerField(help_text='3 year old'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='toddler',
            field=models.IntegerField(help_text='1 -2 year old'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='twaddler',
            field=models.IntegerField(help_text='2-3 year old'),
        ),
    ]
