# Generated by Django 4.2.5 on 2023-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facility', '0004_alter_enrollchild_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirestaff',
            name='earned_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hirestaff',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hirestaff',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
