# Generated by Django 4.2.5 on 2023-11-19 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Facility', '0005_hirestaff_earned_salary_hirestaff_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirestaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
