# Generated by Django 4.2.5 on 2023-11-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facility', '0008_rename_houly_salary_hirestaff_hourly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirestaff',
            name='earned_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hirestaff',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
