# Generated by Django 4.2.5 on 2023-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facility', '0009_alter_hirestaff_earned_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirestaff',
            name='earned_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirestaff',
            name='hours_worked',
            field=models.FloatField(default=0),
        ),
    ]
