# Generated by Django 4.2.5 on 2023-11-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Facility_Administrator',
        ),
    ]
