# Generated by Django 4.2.5 on 2023-11-18 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facility', '0004_alter_enrollchild_child_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('card_no', models.CharField(blank=True, max_length=17)),
                ('month', models.CharField(blank=True, max_length=5)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('name_on_card', models.CharField(blank=True, max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facility.enrollchild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
